include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/kube_image_deploy.yml

stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker tag ${CI_REGISTRY_IMAGE}:latest ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

deploy:
  extends: .k8s_deploy
  stage: deploy
  tags: []
  variables:
    KUBE_DEPLOY_NAMESPACE: default
    KUBE_DEPLOY_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    GIT_STRATEGY: none
    KUBE_DEPLOY_CONTAINER: app
    KUBE_DEPLOY_DEPLOYMENT: node-app
  only:
    - master
  environment:
    name: production
    url: https://app.labamba.space
